-- Test: Select single column (mpg)
df = read_csv("tests/golden/data/mtcars.csv")
result = df |> select("mpg")
write_csv(result, "tests/golden/t_outputs/mtcars_select_mpg.csv")
print("✓ select(mpg) complete")
