[project]
name = "tlang"
description = ""
authors = []

[dependencies]

[r-dependencies]
packages = ["dplyr", "readr", "testthat", "arrow", "jsonlite"]

[py-dependencies]
version = "python314"
packages = ["pandas", "numpy", "onnxruntime", "pyarrow", "skl2onnx"]

[jl-dependencies]
version = "lts"
packages = ["CSV", "DataFrames", "JSON", "Arrow", "ONNX", "ONNXRunTime", "CairoMakie", "Plots", "TidierPlots"]

[additional-tools]
packages = []

[latex]
packages = []

[t]
min_version = "0.53.2"

[nixpkgs]
date = ""

