(* src/packages/stats/predict.ml *)
open Ast

(** predict(df, model) — performs native prediction for a linear model.
    Inspired by tidypredict. *)
(*
--# Linear Model Prediction
--#
--# Calculates predicted values for a linear model object.
--# Supports models generated by lm() or imported via PMML.
--#
--# @name predict
--# @param data :: DataFrame The new data used for prediction.
--# @param model :: Model The linear model object.
--# @return :: Vector The predicted values.
--# @example
--#   model = lm(mpg ~ wt + hp, data: mtcars)
--#   preds = predict(mtcars, model)
--# @family stats
--# @seealso lm
--# @export
*)
let register env =
  Env.add "predict"
    (make_builtin ~name:"predict" 2 (fun args _env ->
      match args with
      | [VDataFrame df; VDict pairs] ->
        (* Extract coefficients and intercept *)
        let coeffs = match List.assoc_opt "coefficients" pairs with
          | Some (VDict c) -> c
          | _ -> []
        in
        
        if coeffs = [] then
          Error.type_error "Function `predict` expects a model with a `coefficients` dictionary."
        else
          let intercept = ref 0.0 in
          let terms = ref [] in
          
          List.iter (fun (name, v) ->
            match v with
            | VFloat f ->
                if name = "(Intercept)" then
                  intercept := f
                else
                  terms := (name, f) :: !terms
            | _ -> ()
          ) coeffs;
          
          let nrows = Arrow_table.num_rows df.arrow_table in
          let out = Array.make nrows 0.0 in
          let na_rows = Array.make nrows false in
          
          (* Basic vectorized prediction: y = b0 + sum(bi * xi) *)
          for i = 0 to nrows - 1 do
            out.(i) <- !intercept;
          done;
          
          let success = ref true in
          let error_msg = ref "" in
          
          List.iter (fun (name, coef) ->
            if !success then
              match Arrow_table.get_column df.arrow_table name with
              | None ->
                  success := false;
                  error_msg := Printf.sprintf "Column `%s` not found in DataFrame for prediction." name
              | Some col ->
                  for i = 0 to nrows - 1 do
                    match Arrow_table.get_float col i with
                    | Some x -> out.(i) <- out.(i) +. (coef *. x)
                    | None -> na_rows.(i) <- true (* Propagate NA: missing predictor yields NA prediction *)
                  done
          ) !terms;
          
          if not !success then Error.make_error KeyError !error_msg
          else 
            let link = match List.assoc_opt "link" pairs with
              | Some (VString l) -> String.lowercase_ascii l
              | _ -> "identity"
            in
            
            let apply_link_inv eta =
              match link with
              | "identity" -> eta
              | "logit" -> 1.0 /. (1.0 +. exp(-. eta))
              | "log" -> exp eta
              | "inverse" -> 1.0 /. eta
              | "sqrt" -> eta *. eta
              | "cloglog" -> 1.0 -. exp(-. exp eta)
              | "probit" ->
                  let a1 =  0.254829592 in
                  let a2 = -0.284496736 in
                  let a3 =  1.421413741 in
                  let a4 = -1.453152027 in
                  let a5 =  1.061405429 in
                  let p  =  0.3275911 in
                  let sign = if eta < 0.0 then -1.0 else 1.0 in
                  let x = Float.abs eta /. sqrt 2.0 in
                  let t = 1.0 /. (1.0 +. p *. x) in
                  let y = 1.0 -. (((((a5 *. t +. a4) *. t) +. a3) *. t +. a2) *. t +. a1) *. t *. exp (-. x *. x) in
                  0.5 *. (1.0 +. sign *. y)
              | _ -> eta (* Default to identity if unknown *)
            in
            
            VVector (Array.mapi (fun i x -> 
              if na_rows.(i) then VNA NAFloat 
              else VFloat (apply_link_inv x)
            ) out)

      | [VDataFrame _; _] ->
          Error.type_error "Function `predict` expects a model (Dict) as second argument."
      | [_; _] ->
          Error.type_error "Function `predict` expects a DataFrame as first argument."
      | _ ->
          Error.make_error ArityError "Function `predict` expects 2 arguments."
    ))
    env
