(* src/packages/stats/predict.ml *)
open Ast

(** predict(df, model) — performs native prediction for a linear model.
    Inspired by tidypredict. *)
(*
--# Linear Model Prediction
--#
--# Calculates predicted values for a linear model object.
--# Supports models generated by lm() or imported via PMML.
--#
--# @name predict
--# @param data :: DataFrame The new data used for prediction.
--# @param model :: Model The linear model object.
--# @return :: Vector The predicted values.
--# @example
--#   model = lm(mpg ~ wt + hp, data: mtcars)
--#   preds = predict(mtcars, model)
--# @family stats
--# @seealso lm
--# @export
*)
let register env =
  Env.add "predict"
    (make_builtin_named ~name:"predict" ~variadic:true 0 (fun args _env ->
      let named = List.filter_map (fun (n, v) -> match n with Some name -> Some (name, v) | None -> None) args in
      let positional = List.filter_map (fun (n, v) -> match n with None -> Some v | Some _ -> None) args in
      let data_v = match List.assoc_opt "data" named with
        | Some v -> Some v
        | None -> (match positional with v :: _ -> Some v | [] -> None)
      in
      let model_v = match List.assoc_opt "model" named with
        | Some v -> Some v
        | None -> (match positional with _ :: v :: _ -> Some v | _ -> (match positional with v :: _ when data_v <> Some v -> Some v | _ -> None))
      in
      match (data_v, model_v) with
      | (Some (VDataFrame df), Some (VDict pairs)) ->
        (* Extract coefficients and intercept *)
        let coeffs = match List.assoc_opt "coefficients" pairs with
          | Some (VDict c) -> c
          | _ -> []
        in
        
        if coeffs = [] then
          Error.type_error "Function `predict` expects a model with a `coefficients` dictionary."
        else
          let intercept = ref 0.0 in
          let terms = ref [] in
          
          List.iter (fun (name, v) ->
            match v with
            | VFloat f ->
                if name = "(Intercept)" || name = "Intercept" || name = "const" then
                  intercept := f
                else
                  terms := (name, f) :: !terms
            | _ -> ()
          ) coeffs;
          
          let nrows = Arrow_table.num_rows df.arrow_table in
          let out = Array.make nrows 0.0 in
          let na_rows = Array.make nrows false in
          
          (* Basic vectorized prediction: y = b0 + sum(bi * xi) *)
          for i = 0 to nrows - 1 do
            out.(i) <- !intercept;
          done;
          
          let success = ref true in
          let error_msg = ref "" in
          
          let string_cols = 
            Arrow_table.column_names df.arrow_table 
            |> List.filter (fun n -> match Arrow_table.column_type df.arrow_table n with Some ArrowString -> true | _ -> false)
          in

          let get_part_value part row_idx =
            match Arrow_table.get_column df.arrow_table part with
            | Some col -> Arrow_table.get_float col row_idx
            | None ->
                let res = ref None in
                List.iter (fun col_name ->
                  if !res = None && String.starts_with ~prefix:col_name part then
                    let level = String.sub part (String.length col_name) (String.length part - String.length col_name) in
                    if level <> "" then (
                      match Arrow_table.get_column df.arrow_table col_name with
                      | Some col ->
                          (match Arrow_table.get_string col row_idx with
                           | Some v -> res := Some (if v = level then 1.0 else 0.0)
                           | None -> ())
                      | _ -> ()
                    )
                ) string_cols;
                !res
          in

          let get_term_value term row_idx =
            if String.contains term ':' then
              let parts = String.split_on_char ':' term in
              let rec loop acc = function
                | [] -> Some acc
                | p :: rest ->
                    (match get_part_value p row_idx with
                     | Some v -> loop (acc *. v) rest
                     | None -> None)
              in loop 1.0 parts
            else
              get_part_value term row_idx
          in

          let is_part_matchable part =
            Arrow_table.has_column df.arrow_table part ||
            List.exists (fun col_name -> 
              String.starts_with ~prefix:col_name part && 
              (String.length part > String.length col_name)
            ) string_cols
          in

          let is_term_matchable term =
            if String.contains term ':' then
              List.for_all is_part_matchable (String.split_on_char ':' term)
            else is_part_matchable term
          in

          List.iter (fun (name, coef) ->
            if !success then (
              if not (is_term_matchable name) then (
                success := false;
                error_msg := Printf.sprintf "Predictor `%s` not found in DataFrame for prediction and could not be resolved as a factor level." name
              ) else (
                for i = 0 to nrows - 1 do
                  if not na_rows.(i) then
                    match get_term_value name i with
                    | Some x -> out.(i) <- out.(i) +. (coef *. x)
                    | None -> na_rows.(i) <- true
                done
              )
            )
          ) !terms;
          
          if not !success then Error.make_error KeyError !error_msg
          else 
            let link = match List.assoc_opt "link" pairs with
              | Some (VString l) -> String.lowercase_ascii l
              | _ -> "identity"
            in
            
            let apply_link_inv eta =
              match link with
              | "identity" -> eta
              | "logit" -> 1.0 /. (1.0 +. exp(-. eta))
              | "log" -> exp eta
              | "inverse" -> 1.0 /. eta
              | "sqrt" -> eta *. eta
              | "cloglog" -> 1.0 -. exp(-. exp eta)
              | "probit" ->
                  let a1 =  0.254829592 in
                  let a2 = -0.284496736 in
                  let a3 =  1.421413741 in
                  let a4 = -1.453152027 in
                  let a5 =  1.061405429 in
                  let p  =  0.3275911 in
                  let sign = if eta < 0.0 then -1.0 else 1.0 in
                  let x = Float.abs eta /. sqrt 2.0 in
                  let t = 1.0 /. (1.0 +. p *. x) in
                  let y = 1.0 -. (((((a5 *. t +. a4) *. t) +. a3) *. t +. a2) *. t +. a1) *. t *. exp (-. x *. x) in
                  0.5 *. (1.0 +. sign *. y)
              | _ -> eta (* Default to identity if unknown *)
            in
            
            VVector (Array.mapi (fun i x -> 
              if na_rows.(i) then VNA NAFloat 
              else VFloat (apply_link_inv x)
            ) out)

      | (Some (VDataFrame _), _) ->
          Error.type_error "Function `predict` expects a model (Dict) as second argument."
      | (Some _, _) ->
          Error.type_error "Function `predict` expects a DataFrame as first argument."
      | _ ->
          Error.make_error ArityError "Function `predict` expects 2 arguments (data, model)."
    ))
    env
