open Ast
open Pipeline_utils

let ensure_dir path =
  if Sys.file_exists path then
    if Sys.is_directory path then Ok ()
    else Error (Error.make_error FileError (Printf.sprintf "`%s` exists but is not a directory." path))
  else
    match Sys.command (Printf.sprintf "mkdir -p %s" (Filename.quote path)) with
    | 0 -> Ok ()
    | _ -> Error (Error.make_error FileError (Printf.sprintf "Failed to create directory `%s`." path))

let ensure_pipeline_nix p =
  if Sys.file_exists Builder_utils.pipeline_nix_path then Ok false
  else
    match Builder.populate_pipeline ~build:false p with
    | Ok _ -> Ok true
    | Error msg -> Error (Error.make_error StructuralError msg)

let ci_flake_content () =
  {|{
  description = "Standalone T pipeline CI flake generated by pipeline_ci()";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
    t-lang.url = "github:b-rodrigues/tlang";
  };

  outputs = { self, nixpkgs, flake-utils, t-lang }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pipeline = import ../pipeline.nix { inherit system; };
      in {
        packages.default = pipeline.pipeline_output;
        packages.pipeline = pipeline.pipeline_output;
        checks.pipeline = pipeline.pipeline_output;
      });
}
|}

let workflow_content cache =
  let cachix_step =
    match cache with
    | Some c when String.trim c <> "" ->
        Printf.sprintf {|      - name: Configure Cachix
        uses: cachix/cachix-action@v15
        with:
          name: %s
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
|} c
    | _ -> ""
  in
  Printf.sprintf {|name: T pipeline

on:
  push:
  pull_request:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
%s      - name: Build pipeline
        run: nix build ./_pipeline/ci#pipeline --accept-flake-config --print-build-logs
|} cachix_step

let write_text_file path content =
  match Builder_utils.write_file path content with
  | Ok () -> Ok ()
  | Error msg -> Error (Error.make_error FileError msg)

(*
--# Generate CI flake for a pipeline
--#
--# Reuses an existing `_pipeline/pipeline.nix` when one has already been created by `build_pipeline()` or `populate_pipeline()`.
--# If the pipeline Nix file is missing, generates it once, then writes a standalone CI flake under `_pipeline/ci/`.
--# The generated flake can be built with `nix build ./_pipeline/ci#pipeline` in any Nix-enabled CI runner.
--# Optionally writes a GitHub Actions workflow that installs Nix, configures Cachix, and builds the flake.
--#
--# @name pipeline_ci
--# @param p :: Pipeline The pipeline to export for CI.
--# @param output_dir :: String = "_pipeline/ci" Directory where the CI flake is written.
--# @param workflow :: Bool = false Whether to also write `.github/workflows/t-pipeline.yml`.
--# @param cache :: String (Optional) Cachix cache name for the generated workflow.
--# @return :: Dict Paths and commands for the generated CI integration.
--# @family pipeline
--# @export
*)
let register env =
  let get_arg name pos default named_args =
    match List.assoc_opt name (List.filter_map (fun (k, v) -> match k with Some s -> Some (s, v) | None -> None) named_args) with
    | Some v -> (true, v)
    | None ->
        let positionals = List.filter_map (fun (k, v) -> match k with None -> Some v | Some _ -> None) named_args in
        match nth_safe (pos - 1) positionals with
        | Some v -> (true, v)
        | None -> (false, default)
  in
  let ci_fn named_args _env =
    let named_keys = List.filter_map (fun (k, _) -> k) named_args in
    let positional_count = List.length (List.filter (fun (k, _) -> k = None) named_args) in
    match List.find_opt (fun k -> not (List.mem k ["p"; "output_dir"; "workflow"; "cache"])) named_keys with
    | Some k -> Error.type_error (Printf.sprintf "pipeline_ci: unknown argument '%s'" k)
    | None when positional_count > 4 ->
        Error.make_error ArityError
          (Printf.sprintf "Function `pipeline_ci` accepts at most 4 positional arguments but received %d." positional_count)
    | None ->
        match get_arg "p" 1 (VNA NAGeneric) named_args with
        | _, VPipeline p ->
            let output_dir_provided, output_dir_val = get_arg "output_dir" 2 (VString "_pipeline/ci") named_args in
            let workflow_provided, workflow_val = get_arg "workflow" 3 (VBool false) named_args in
            let cache_provided, cache_val = get_arg "cache" 4 (VNA NAGeneric) named_args in
            let output_dir_result =
              match output_dir_val with
              | VString s when String.trim s <> "" -> Ok s
              | VString _ -> Error (Error.value_error "Function `pipeline_ci` expects `output_dir` to be a non-empty String.")
              | _ when output_dir_provided -> Error (Error.type_error "Function `pipeline_ci` expects `output_dir` to be a String.")
              | _ -> Ok "_pipeline/ci"
            in
            let workflow_result =
              match workflow_val with
              | VBool b -> Ok b
              | _ when workflow_provided -> Error (Error.type_error "Function `pipeline_ci` expects `workflow` to be a Bool.")
              | _ -> Ok false
            in
            let cache_result =
              match cache_val with
              | VString s -> Ok (Some s)
              | VNA _ -> Ok None
              | _ when cache_provided -> Error (Error.type_error "Function `pipeline_ci` expects `cache` to be a String.")
              | _ -> Ok None
            in
            (match output_dir_result, workflow_result, cache_result with
             | Error e, _, _ | _, Error e, _ | _, _, Error e -> e
             | Ok output_dir, Ok workflow, Ok cache ->
                 (match ensure_pipeline_nix p with
                  | Error e -> e
                  | Ok generated_pipeline_nix ->
                      match ensure_dir output_dir with
                      | Error e -> e
                      | Ok () ->
                          let flake_path = Filename.concat output_dir "flake.nix" in
                          match write_text_file flake_path (ci_flake_content ()) with
                          | Error e -> e
                          | Ok () ->
                              if workflow then
                                match ensure_dir ".github/workflows" with
                                | Error e -> e
                                | Ok () ->
                                    let workflow_path = ".github/workflows/t-pipeline.yml" in
                                    (match write_text_file workflow_path (workflow_content cache) with
                                     | Error e -> e
                                     | Ok () -> VDict [
                                         ("flake", VString flake_path);
                                         ("workflow", VString workflow_path);
                                         ("build_command", VString (Printf.sprintf "nix build ./%s#pipeline --accept-flake-config --print-build-logs" output_dir));
                                         ("generated_pipeline_nix", VBool generated_pipeline_nix);
                                       ])
                              else VDict [
                                ("flake", VString flake_path);
                                ("workflow", VNA NAGeneric);
                                ("build_command", VString (Printf.sprintf "nix build ./%s#pipeline --accept-flake-config --print-build-logs" output_dir));
                                ("generated_pipeline_nix", VBool generated_pipeline_nix);
                              ]))
        | _ -> Error.type_error "Function `pipeline_ci` expects a Pipeline."
  in
  Env.add "pipeline_ci" (make_builtin_named ~name:"pipeline_ci" ~variadic:true 1 ci_fn) env
