name: Build and Cache
on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '0 3 * * *' # Every night at 03:00 AM

jobs:
  build:
    strategy:
      matrix:
        system:
          - x86_64-linux
          - aarch64-linux
          - aarch64-darwin
    runs-on: ${{ contains(matrix.system, 'darwin') && 'macos-latest' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      
      - uses: cachix/cachix-action@v15
        with:
          name: rstats-on-nix
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      
      - name: Build T and push to Cachix
        run: |
          nix build .#default --print-build-logs
          RESULT_PATH="$(python3 -c 'import os; print(os.path.realpath("result"))')"
          cachix push rstats-on-nix "$RESULT_PATH"
