name: Trigger Demo Actions

env:
  TLANG_SKIP_PKG_CHECK: "1"

on:
  workflow_run:
    workflows: ["Build and Cache"]
    types:
      - completed
  pull_request:
  workflow_dispatch:


jobs:
  trigger-demo:
    if: ${{ (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch event to t_demos
        env:
          GH_TOKEN: ${{ secrets.TRIGGER_DEMOS }}
          REPO: ${{ github.event.pull_request.head.repo.full_name != '' && github.event.pull_request.head.repo.full_name || github.repository }}
          SHA: ${{ github.event.pull_request.head.sha != '' && github.event.pull_request.head.sha || github.sha }}
        run: |
          gh api repos/b-rodrigues/t_demos/dispatches \
            --method POST \
            --field event_type=trigger-demo \
            --field client_payload[repo]="$REPO" \
            --field client_payload[sha]="$SHA"
